# -*-coding:utf-8-*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import correspondence_pb2 as correspondence__pb2


class BackendStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SayHello = channel.unary_unary(
        '/Backend/SayHello',
        request_serializer=correspondence__pb2.HelloRequest.SerializeToString,
        response_deserializer=correspondence__pb2.HelloResponse.FromString,
        )
    self.SayHelloAgain = channel.unary_unary(
        '/Backend/SayHelloAgain',
        request_serializer=correspondence__pb2.HelloRequest.SerializeToString,
        response_deserializer=correspondence__pb2.HelloResponse.FromString,
        )
    self.GetRecordsCount = channel.unary_unary(
        '/Backend/GetRecordsCount',
        request_serializer=correspondence__pb2.RequestStruct.SerializeToString,
        response_deserializer=correspondence__pb2.ResponseStruct.FromString,
        )
    self.GetAllNotes = channel.unary_unary(
        '/Backend/GetAllNotes',
        request_serializer=correspondence__pb2.RequestStruct.SerializeToString,
        response_deserializer=correspondence__pb2.ResponseStruct.FromString,
        )
    self.InsertANote = channel.unary_unary(
        '/Backend/InsertANote',
        request_serializer=correspondence__pb2.RequestStruct.SerializeToString,
        response_deserializer=correspondence__pb2.ResponseStruct.FromString,
        )
    self.ModifyTheNote = channel.unary_unary(
        '/Backend/ModifyTheNote',
        request_serializer=correspondence__pb2.RequestStruct.SerializeToString,
        response_deserializer=correspondence__pb2.ResponseStruct.FromString,
        )
    self.VoidTheNote = channel.unary_unary(
        '/Backend/VoidTheNote',
        request_serializer=correspondence__pb2.RequestStruct.SerializeToString,
        response_deserializer=correspondence__pb2.ResponseStruct.FromString,
        )
    self.GetAllUsers = channel.unary_unary(
        '/Backend/GetAllUsers',
        request_serializer=correspondence__pb2.RequestStruct.SerializeToString,
        response_deserializer=correspondence__pb2.ResponseStruct.FromString,
        )
    self.DeleteTheUser = channel.unary_unary(
        '/Backend/DeleteTheUser',
        request_serializer=correspondence__pb2.RequestStruct.SerializeToString,
        response_deserializer=correspondence__pb2.ResponseStruct.FromString,
        )
    self.InsertAUser = channel.unary_unary(
        '/Backend/InsertAUser',
        request_serializer=correspondence__pb2.RequestStruct.SerializeToString,
        response_deserializer=correspondence__pb2.ResponseStruct.FromString,
        )
    self.ModifyTheUser = channel.unary_unary(
        '/Backend/ModifyTheUser',
        request_serializer=correspondence__pb2.RequestStruct.SerializeToString,
        response_deserializer=correspondence__pb2.ResponseStruct.FromString,
        )
    self.GetTheUser = channel.unary_unary(
        '/Backend/GetTheUser',
        request_serializer=correspondence__pb2.RequestStruct.SerializeToString,
        response_deserializer=correspondence__pb2.ResponseStruct.FromString,
        )


class BackendServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SayHello(self, request, context):
    """测试接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SayHelloAgain(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRecordsCount(self, request, context):
    """正式接口
    ->数据交互相关接口
    ->->共用接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllNotes(self, request, context):
    """->->公告相关接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InsertANote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ModifyTheNote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def VoidTheNote(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAllUsers(self, request, context):
    """->->用户相关接口
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTheUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InsertAUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ModifyTheUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTheUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BackendServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SayHello': grpc.unary_unary_rpc_method_handler(
          servicer.SayHello,
          request_deserializer=correspondence__pb2.HelloRequest.FromString,
          response_serializer=correspondence__pb2.HelloResponse.SerializeToString,
      ),
      'SayHelloAgain': grpc.unary_unary_rpc_method_handler(
          servicer.SayHelloAgain,
          request_deserializer=correspondence__pb2.HelloRequest.FromString,
          response_serializer=correspondence__pb2.HelloResponse.SerializeToString,
      ),
      'GetRecordsCount': grpc.unary_unary_rpc_method_handler(
          servicer.GetRecordsCount,
          request_deserializer=correspondence__pb2.RequestStruct.FromString,
          response_serializer=correspondence__pb2.ResponseStruct.SerializeToString,
      ),
      'GetAllNotes': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllNotes,
          request_deserializer=correspondence__pb2.RequestStruct.FromString,
          response_serializer=correspondence__pb2.ResponseStruct.SerializeToString,
      ),
      'InsertANote': grpc.unary_unary_rpc_method_handler(
          servicer.InsertANote,
          request_deserializer=correspondence__pb2.RequestStruct.FromString,
          response_serializer=correspondence__pb2.ResponseStruct.SerializeToString,
      ),
      'ModifyTheNote': grpc.unary_unary_rpc_method_handler(
          servicer.ModifyTheNote,
          request_deserializer=correspondence__pb2.RequestStruct.FromString,
          response_serializer=correspondence__pb2.ResponseStruct.SerializeToString,
      ),
      'VoidTheNote': grpc.unary_unary_rpc_method_handler(
          servicer.VoidTheNote,
          request_deserializer=correspondence__pb2.RequestStruct.FromString,
          response_serializer=correspondence__pb2.ResponseStruct.SerializeToString,
      ),
      'GetAllUsers': grpc.unary_unary_rpc_method_handler(
          servicer.GetAllUsers,
          request_deserializer=correspondence__pb2.RequestStruct.FromString,
          response_serializer=correspondence__pb2.ResponseStruct.SerializeToString,
      ),
      'DeleteTheUser': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTheUser,
          request_deserializer=correspondence__pb2.RequestStruct.FromString,
          response_serializer=correspondence__pb2.ResponseStruct.SerializeToString,
      ),
      'InsertAUser': grpc.unary_unary_rpc_method_handler(
          servicer.InsertAUser,
          request_deserializer=correspondence__pb2.RequestStruct.FromString,
          response_serializer=correspondence__pb2.ResponseStruct.SerializeToString,
      ),
      'ModifyTheUser': grpc.unary_unary_rpc_method_handler(
          servicer.ModifyTheUser,
          request_deserializer=correspondence__pb2.RequestStruct.FromString,
          response_serializer=correspondence__pb2.ResponseStruct.SerializeToString,
      ),
      'GetTheUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetTheUser,
          request_deserializer=correspondence__pb2.RequestStruct.FromString,
          response_serializer=correspondence__pb2.ResponseStruct.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Backend', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
